apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  namespace: playground-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-deployment
  template:
    metadata:
      labels:
        app: playground-deployment
    spec:
      containers:
      - name: playground-deployment
        image: rdockeruser/playground
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: playground-service
spec:
  selector:
    app: playground-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
